CREATE TABLE INSTRUCTOR (
    ID                     INT(3) NOT NULL,
    INSTRUCTOR_FIRST_NAME  VARCHAR(15) NOT NULL,
    INSTRUCTOR_LAST_NAME   VARCHAR(15) NOT NULL,
    INSTRUCTOR_EMAIL       VARCHAR(30) NOT NULL,
    CONSTRAINT INSTRUCTOR_PK PRIMARY KEY (ID),
    CONSTRAINT INSTRUCTOR_EMAIL_UNIQUE UNIQUE (INSTRUCTOR_EMAIL)
);

CREATE TABLE INSTRUCTOR_DETAIL (
    ID                    INT(3) NOT NULL,
    YOUTUBE_CHANNEL       VARCHAR(30) NOT NULL,
    CHANNEL_DESCRIPTION   VARCHAR(300) NOT NULL,
    NO_OF_SUBSCRIBER      INT(20) NOT NULL,
    INSTRUCTOR_ID         INT(3) NOT NULL,
    CONSTRAINT INSTRUCTOR_DETAIL_PK PRIMARY KEY (ID),
	CONSTRAINT SUBSCRIBER_CHECK CHECK (NO_OF_SUBSCRIBER >= 0),
    CONSTRAINT YOUTUBE_CHANNEL_UNIQUE UNIQUE (YOUTUBE_CHANNEL),
    CONSTRAINT INSTRUCTOR_ID_FK1 FOREIGN KEY (INSTRUCTOR_ID)
        REFERENCES INSTRUCTOR ( ID )
);

CREATE TABLE COURSE (
    ID                 INT(4) NOT NULL,
    COURSE_NAME        VARCHAR(50) NOT NULL,
	PRICE 			   INT(7),
	COURSE_DESCRIPTION VARCHAR(200) NOT NULL,
    INSTRUCTOR_ID      INT(3) NOT NULL,
    CONSTRAINT COURSE_PK PRIMARY KEY (ID),
    CONSTRAINT INSTRUCTOR_ID_FK2 FOREIGN KEY (INSTRUCTOR_ID)
        REFERENCES INSTRUCTOR (ID)
);

CREATE TABLE REVIEW (
    ID          INT(5) NOT NULL,
    COMMENTS    VARCHAR(300) NOT NULL,
    COURSE_ID   INT(4) NOT NULL,
    CONSTRAINT REVIEW_PK PRIMARY KEY (ID),
    CONSTRAINT COURSE_ID_FK1 FOREIGN KEY (COURSE_ID)
        REFERENCES COURSE (ID)
);

CREATE TABLE STUDENT (
    ID                   INT(3) NOT NULL,
    ROLL                 INT(3) NOT NULL,
    STUDENT_FIRST_NAME   VARCHAR(15) NOT NULL,
    STUDENT_LAST_NAME    VARCHAR(15),
    STUDENT_EMAIL        VARCHAR(30) NOT NULL,
    CONSTRAINT STUDENT_PK PRIMARY KEY (ID),
    CONSTRAINT STUDENT_EMAIL_UNIQUE UNIQUE (STUDENT_EMAIL)
);

CREATE TABLE COURSE_STUDENT (
    STUDENT_ID   INT(3) NOT NULL,
    COURSE_ID    INT(4) NOT NULL,
    CONSTRAINT COURSE_STUDENT_PK PRIMARY KEY (COURSE_ID, STUDENT_ID),
    CONSTRAINT STUDENT_ID_FK FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (ID),
    CONSTRAINT COURSE_ID_FK2 FOREIGN KEY (COURSE_ID)
        REFERENCES COURSE (ID)
);

CREATE TABLE STUDENT_COURSE (
    ID                 INT(4) NOT NULL,
    STUDENT_ID         INT(3) NOT NULL,
    COURSE_ID          INT(4) NOT NULL,
    DATE_OF_PURCHASE   DATE,
    CONSTRAINT STUDENT_COURSE_PK PRIMARY KEY (ID),
    CONSTRAINT STUDENT_COURSE_UNIQUE UNIQUE (STUDENT_ID, COURSE_ID),
    CONSTRAINT STUDENT_ID_FK2 FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (ID),
    CONSTRAINT COURSE_ID_FK3 FOREIGN KEY (COURSE_ID)
        REFERENCES COURSE (ID)
);

CREATE TABLE INSTRUCTOR_JOB_DETAIL (
    ID                   INT(3) NOT NULL,
    ORGANIZATION         VARCHAR(50) NOT NULL,
    OFFICE_ADDRESS       VARCHAR(200),
    OFFICE_HR_PHONE_NO   INT(10),
    OFFICE_HR_EMAIL      VARCHAR(30),
    INSTRUCTOR_ID        INT(3) NOT NULL,
    CONSTRAINT INSTRUCTOR_JOB_DETAIL_PK PRIMARY KEY (ID),
	CONSTRAINT INSTRUCTOR_JOB_DETAIL_UNIQUE UNIQUE (INSTRUCTOR_ID),
    CONSTRAINT INSTRUCTOR_ID_FK3 FOREIGN KEY (INSTRUCTOR_ID)
        REFERENCES INSTRUCTOR (ID)
);